services:
  #Dans confif/config/network.xml Dans la balise BaseUrl, ajouter l'endpoint voulu
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /path/to/data/media:/media
    restart: 'unless-stopped'